const GAME_ITEMS_V2 = {
    wearable: [
        {
            key: 'eveningDress',
            name: 'Evening dress',
            description: 'Perfect for special events + quite sexy!',
            slot: 'body',
            mediaKey: 'wearable.eveningDress',
            mediaPaperDollKey: 'paperDoll.body.upper.eveningDress',
            allure: 20,
            obscenity: 5,
            price: 150,
            type: 'clothes'
        },
        {
            key: 'miniskirt',
            name: 'Miniskirt',
            slot: 'lowerBody',
            image: 'pics/object/MSkirt.jpg',
            description: 'Very attractive and comfortable!',
            mediaKey: 'wearable.miniskirt',
            mediaPaperDollKey: 'paperDoll.body.upper.eveningDress',
            allure: 30,
            obscenity: 10,
            price: 120,
            type: 'clothes',
        },
        {
            key: 'officeSuit',
            name: 'Office suit',
            slot: 'body',
            image: 'pics/object/OfficeSuit.jpg',
            description: 'Strict and firm',
            mediaKey: 'wearable.officeSuit',
            mediaPaperDollKey: 'paperDoll.body.upper.officeSuit',
            allure: 10,
            obscenity: 0,
            price: 90,
            type: 'clothes',
        },
        {
            key: 'sportOutfit',
            name: 'Sport outfit',
            slot: 'body',
            image: 'pics/object/SportOutfit.jpg',
            description: 'You can do sports in it. Not for everyday wear',
            mediaKey: 'wearable.sportOutfit',
            mediaPaperDollKey: 'paperDoll.body.upper.eveningDress',
            allure: 3,
            obscenity: 0,
            price: 70,
            type: 'clothes',
        },
        {
            key: 'bikini',
            name: 'Bikini',
            slot: 'body',
            image: 'pics/wearable/Bikini.jpg',
            description: 'You can swim in it. Not for everyday wear',
            mediaKey: 'wearable.bikini',
            mediaPaperDollKey: 'paperDoll.body.upper.eveningDress',
            allure: 20,
            obscenity: 0,
            price: 60,
            type: 'clothes',
        },
        {
            key: 'shortsAndShirt',
            name: 'Shorts with t-shirt',
            slot: 'body',
            image: 'pics/object/shorts_with_tshirt.jpg',
            description: 'Very comfortable and open clothing...',
            mediaKey: 'wearable.shortsAndShirt',
            mediaPaperDollKey: 'paperDoll.body.upper.eveningDress',
            allure: 30,
            obscenity: 0,
            price: 70,
            type: 'clothes',
        },
        {
            key: 'stockings',
            name: 'Stockings',
            slot: 'stockings',
            image: 'pics/object/Stockings.jpg',
            description: "Sexy as hell, isn't it?",
            mediaKey: 'wearable.stockings',
            mediaPaperDollKey: 'paperDoll.body.upper.eveningDress',
            allure: 5,
            obscenity: 0,
            price: 80,
            type: 'clothes',
        },
        {
            key: 'choker',
            name: 'Choker',
            slot: 'neck',
            image: 'pics/wearable/Choker.jpg',
            description: 'Simple and sexy:3',
            mediaKey: 'wearable.choker',
            mediaPaperDollKey: 'paperDoll.body.upper.eveningDress',
            allure: 5,
            obscenity: 10,
            price: 40,
            type: 'accessory',
        },
        {
            key: 'plainBlackBra',
            name: 'Plain Black Bra',
            slot: 'bra',
            price: 40,
            image: 'pics/look/lingerie/bra/default_bra.jpg',
            description: 'A plain black bra.',
            mediaKey: 'wearable.plainBlackBra',
            mediaPaperDollKey: 'paperDoll.body.upper.bra',
            allure: 2,
            obscenity: 1,
            type: 'lingerie',
        },
        {
            key: 'plainBlackPanties',
            name: 'Plain Black Panties',
            slot: 'panties',
            price: 30,
            image: 'pics/look/lingerie/panties/default_panties.jpg',
            description: 'A plain black pair of panties.',
            mediaKey: 'wearable.plainBlackPanties',
            mediaPaperDollKey: 'paperDoll.body.lower.panties.defaultPanties',
            allure: 2,
            obscenity: 1,
            type: 'lingerie',
        },
        {
            key: 'blackMiniGString',
            name: 'Transparent Mini G-String',
            slot: 'panties',
            price: 60,
            image: 'pics/look/lingerie/panties/transparentBlackMiniGString.jpg',
            description: 'A plain black pair of panties.',
            mediaKey: 'wearable.blackMiniGString',
            mediaPaperDollKey: 'paperDoll.body.lower.panties.defaultPanties',
            allure: 15,
            obscenity: 5,
            type: 'lingerie',
        },
        {
            key: 'schoolUniform',
            name: 'School uniform',
            slot: 'body',
            price: 60,
            image: 'pics/object/SchoolUniform.jpg',
            description: 'You must wear this at school',
            mediaKey: 'wearable.schoolUniform',
            mediaPaperDollKey: 'paperDoll.body.upper.schoolUniform',
            allure: 5,
            obscenity: 2,
            type: 'clothes',
            category: 'suit, school',
        },
        {
            key: 'homeTShirt',
            name: 'Home t-shirt',
            slot: 'upper',
            price: 60,
            image: 'pics/PaperDoll/UpperBody/MainClothes/Home t-shirta.png',
            description: 'Regular clothes, nice and comfortable.',
            mediaKey: 'wearable.homeTShirt',
            mediaPaperDollKey: 'paperDoll.body.upper.homeTShirt',
            allure: 2,
            obscenity: 1,
            type: 'clothes',
            category: 'usual',
        },
        {
            key: 'usualClothes',
            name: 'Usual clothes',
            slot: 'upper',
            price: 60,
            image: 'pics/object/UClothes.jpg',
            description: 'Regular clothes, nice and comfortable.',
            mediaKey: 'wearable.usualClothes',
            mediaPaperDollKey: 'paperDoll.body.upper.usualClothes',
            allure: 5,
            obscenity: 0,
            type: 'clothes',
            category: 'usual',
        },
        {
            key: 'jeans',
            name: 'Jeans',
            slot: 'lower',
            price: 60,
            image: 'pics/PaperDoll/LowerBody/LowerBodyClothes/Jeans.png',
            description: 'Just tight jeans.',
            mediaKey: 'wearable.jeans',
            mediaPaperDollKey: 'paperDoll.body.lower.jeans',
            allure: 5,
            obscenity: 0,
            type: 'clothes',
            category: 'usual',
        },
        {
            key: 'schoolSkirt',
            name: 'School skirt',
            slot: 'lower',
            price: 60,
            image: 'pics/PaperDoll/LowerBody/LowerBodyClothes/School skirt.png',
            description: 'Not very long cute skirt',
            mediaKey: 'wearable.schoolSkirt',
            mediaPaperDollKey: 'paperDoll.body.lower.schoolSkirt',
            allure: 5,
            obscenity: 1,
            type: 'clothes',
            category: 'usual',
        },
        {
            key: 'shortSocks',
            name: 'Short socks',
            slot: 'legs',
            price: 60,
            image: 'pics/PaperDoll/LowerBody/Stockings/Short socks.png',
            description: 'Very comfy white short socks',
            mediaKey: 'wearable.shortSocks',
            mediaPaperDollKey: 'paperDoll.body.lower.shortSocks',
            allure: 0,
            obscenity: 0,
            type: 'clothes',
            category: 'usual',
        },
        {
            key: 'trainers',
            name: 'Trainers',
            slot: 'feet',
            price: 60,
            image: 'pics/PaperDoll/LowerBody/Shoes/Trainers.png',
            description: 'A new pair of cool trainers',
            mediaKey: 'wearable.trainers',
            mediaPaperDollKey: 'paperDoll.body.feet.trainers',
            allure: 0,
            obscenity: 0,
            type: 'clothes',
            category: 'usual',
        },
        {
            key: 'schoolShoes',
            name: 'School shoes',
            slot: 'feet',
            price: 60,
            image: 'pics/PaperDoll/LowerBody/Shoes/School shoes.png',
            description: 'A pair of formal girl shoes.',
            mediaKey: 'wearable.schoolShoes',
            mediaPaperDollKey: 'paperDoll.body.feet.schoolShoes',
            allure: 0,
            obscenity: 0,
            type: 'clothes',
            category: 'usual',
        },
        {
            key: 'plainGoldRing',
            name: 'Plain gold ring',
            slot: 'ring',
            type: 'accessory',
            image: 'pics/object/PGRing.jpg',
            description: 'You have had this ring for as long as you can remember.',
            mediaKey: 'wearable.plainGoldRing',
            price: 70,
            allure: 5,
            obscenity: 0
        },
        {
            key: 'anal_plug',
            name: 'Butt plug',
            slot: 'buttPlug',
            type: 'accessory',
            image: 'pics/wearable/BPlug.jpg',
            description: 'A butt plug, wear everyday.',
            mediaKey: 'wearable.anal_plug',
            mediaPaperDollKey: 'paperDoll.body.lower.buttPlug',
            mediaPaperDollVariant: '',
            price: 70,
            size: 6,
            allure: 0,
            use: 'single',
        },
        {
            key: 'anal_tailplug',
            name: 'Tail butt plug',
            slot: 'buttPlug',
            type: 'accessory',
            image: 'pics/wearable/TBPlug.jpg',
            description: 'Cute and fluffy.',
            mediaKey: 'wearable.anal_tailplug',
            mediaPaperDollKey: 'paperDoll.body.lower.buttPlug',
            mediaPaperDollVariant: 'TailButtPlug',
            price: 110,
            size: 6,
            allure: 0,
            use: 'single',
        },
        {
            key: 'nipple_rings',
            name: 'Nipple rings',
            slot: 'chestAccessory',
            type: 'accessory',
            image: 'pics/object/NPiercing.png',
            description: "That's lovely!",
            mediaKey: 'wearable.nipple_rings',
            mediaPaperDollKey: 'paperDoll.body.upper.nippleRings',
            price: 50,
            allure: 7,
            use: 'single',
        },
        {
            key: 'dildo',
            name: 'Dildo',
            slot: null,
            type: 'toy',
            image: 'pics/object/Dildo.jpg',
            size: 10,
            price: 40,
            description: 'A plain dildo.',
            mediaKey: 'object.dildo',
            color: 'pink',
            use: 'single',
        },
        {
            key: 'gun',
            slot: null,
            type: 'weapon',
            name: 'Sig Sauer 9mm',
            image: 'pics/object/Gun.jpg',
            mediaKey: 'object.gun',
            description: 'This gun will scare away any bad man you might meet!',
            price: 150
        },
        {
            key: 'laptop',
            name: 'Laptop',
            slot: null,
            type: 'computer',
            image: 'pics/object/Laptop.png',
            mediaKey: 'object.laptop',
            description: 'A must have for teenagers!',
            price: 800,
        },
        {
            key: 'webcam',
            name: 'Web cam',
            slot: null,
            type: 'video_camera',
            image: 'pics/personal_items/webcam.jpg',
            mediaKey: 'object.webcam',
            description: 'To chat with your friends and family! And not only... (Requires Laptop)',
            price: 500,
        },
        {
            key: 'makeup_kit',
            name: 'Makeup kit',
            slot: null,
            type: 'cosmetics',
            image: 'pics/personal_items/cosmetics.jpg',
            mediaKey: 'object.makeup_kit',
            description: 'A set of cosmetics for women who want to look stunning and eye-catching!',
            count: 10,
            price: 300,
            use: 'many',
        },
        {
            key: 'lipstick',
            name: 'lipstick',
            slot: null,
            type: 'cosmetics',
            variants: ['red', 'black', 'brown', 'violet', 'pink'],
            image: 'pics/personal_items/lipsticks/red.jpg',
            mediaKey: 'object.lipstick',
            description: 'lipstick',
            count: 30,
            price: 130,
            use: 'many',
        },
        {
            key: 'lipbalm',
            name: 'Lip balm',
            slot: null,
            type: 'cosmetics',
            image: 'pics/personal_items/lipbalm.jpg',
            mediaKey: 'object.lipbalm',
            description: 'Lip balm',
            count: 30,
            price: 100,
            use: 'many',
        },
        {
            key: 'birth_control_pills',
            name: 'Birth control pills',
            slot: null,
            type: 'medical',
            image: 'pics/personal_items/birth_control_pills.jpg',
            mediaKey: 'object.birth_control_pills',
            description: "Who doesn't want a lot of hassle and sleepless nights?",
            count: 10,
            price: 150,
            use: 'many',
        },
        {
            key: 'tampons',
            name: 'Tampons',
            slot: null,
            type: 'hygiene',
            image: 'pics/personal_items/tampons.jpg',
            mediaKey: 'object.tampons',
            description: 'Take on unexpected moments',
            count: 18,
            price: 250,
            use: 'many',
        },
        {
            key: 'vitamins',
            name: 'Vitamins',
            slot: null,
            type: 'medical',
            image: 'pics/personal_items/vitamins.jpg',
            mediaKey: 'object.vitamins',
            description: 'Drink once a day for good health and energy!',
            count: 20,
            price: 200,
            use: 'many',
        },
        {
            key: 'pregnancy_test',
            name: 'Pregnancy test',
            slot: null,
            type: 'medical',
            image: 'pics/personal_items/pregnancy_test.jpg',
            mediaKey: 'object.pregnancy_test',
            description: 'The game started...',
            count: 1,
            price: 100,
            use: 'many',
        },
        {
            key: 'shampoo',
            name: 'Shampoo',
            slot: null,
            type: 'hygiene',
            image: 'pics/personal_items/shampoo.jpg',
            mediaKey: 'object.shampoo',
            description: 'Keeps your body and hair clean',
            count: 20,
            price: 150,
            use: 'many',
        },
        {
            key: 'razors',
            name: 'Razors',
            slot: null,
            type: 'hygiene',
            image: 'pics/personal_items/razors.jpg',
            mediaKey: 'object.razors',
            description: 'Cuts your bush',
            count: 20,
            price: 200,
            use: 'many',
        },
    ]
}

const GAME_ITEMS = {
    clothes: {
        eveningDress: {
            name: 'Evening dress',
            image: 'pics/wearable/EDress.jpg',
            // image: gameMedia.getImage({key: 'wearable.eveningDress'}),
            description: 'Perfect for special events + quite sexy!',
            allure: 20,
            obscenity: 5,
            price: 150,
            type: 'body',
        },
        miniskirt: {
            name: 'Miniskirt',
            image: 'pics/object/MSkirt.jpg',
            description: 'Very attractive and comfortable!',
            allure: 30,
            obscenity: 10,
            price: 120,
            type: 'body',
        },
        officeSuit: {
            name: 'Office suit',
            image: 'pics/object/OfficeSuit.jpg',
            description: 'Strict and firm. You must wear this at work.',
            allure: 10,
            obscenity: 0,
            price: 90,
            type: 'body',
        },
        sportOutfit: {
            name: 'Sport outfit',
            image: 'pics/object/SportOutfit.jpg',
            description: 'You can do sports in it. Not for everyday wear',
            allure: 3,
            obscenity: 0,
            price: 70,
            type: 'body',
        },
        bikini: {
            name: 'Bikini',
            image: 'pics/wearable/Bikini.jpg',
            description: 'You can swim in it. Not for everyday wear',
            allure: 20,
            obscenity: 0,
            price: 60,
            type: 'body',
        },
        shortsAndShirt: {
            name: 'Shorts with t-shirt',
            image: 'pics/object/shorts_with_tshirt.jpg',
            description: 'Very comfortable and open clothing...',
            allure: 30,
            obscenity: 0,
            price: 70,
            type: 'body',
        },
        stockings: {
            name: 'Stockings',
            image: 'pics/object/Stockings.jpg',
            description: "Sexy as hell, isn't it?",
            allure: 5,
            obscenity: 0,
            price: 80,
            type: 'legs',
        },
    },
    accessories: {
        choker: {
            name: 'Choker',
            image: 'pics/wearable/Choker.jpg',
            description: 'Simple and sexy:3',
            allure: 5,
            obscenity: 10,
            price: 40,
            type: 'neck',
        },
    },
    lingerie: {
        plainBlackBra: {
            name: 'Plain Black Bra',
            price: 40,
            image: 'pics/look/lingerie/bra/default_bra.jpg',
            description: 'A plain black bra.',
            allure: 0,
            obscenity: 0,
            type: 'bra',
        },
        plainBlackPanties: {
            name: 'Plain Black Panties',
            price: 30,
            image: 'pics/look/lingerie/panties/default_panties.jpg',
            description: 'A plain black pair of panties.',
            allure: 0,
            obscenity: 0,
            type: 'panties',
        },
        blackMiniGString: {
            name: 'Transparent Mini G-String',
            price: 60,
            image: 'pics/look/lingerie/panties/transparentBlackMiniGString.jpg',
            description: 'A plain black pair of panties.',
            allure: 15,
            obscenity: 5,
            type: 'panties',
        },
        // bras: [
        //     {
        //         name: 'Usual bra',
        //         price: 40,
        //         image: 'pics/usualBra.jpg',
        //     },
        // ],
        // panties: [
        //     {
        //         name: 'Usual panties',
        //         price: 30,
        //         image: 'pics/usualPanties.jpg',
        //     },
        // ],
    },
    erotic_accessories: {
        dildo: {
            name: 'Dildo',
            image: 'pics/object/Dildo.jpg',
            size: 10,
            price: 40,
            description: 'A plain dildo.',
            color: 'pink',
            use: 'single',
        },
        "anal_plug": {
            name: 'Butt plug',
            image: 'pics/wearable/BPlug.jpg',
            description: 'A butt plug, wear everyday.',
            price: 70,
            size: 6,
            allure: 0,
            type: 'back',
            use: 'single',
        },
        "anal_tailplug": {
            name: 'Tail butt plug',
            image: 'pics/wearable/TBPlug.jpg',
            description: 'Cute and fluffy.',
            price: 110,
            size: 6,
            allure: 0,
            type: 'back',
            use: 'single',
        },
        "nipple_rings": {
            name: 'Nipple rings',
            image: 'pics/object/NPiercing.png',
            description: "That's lovely!",
            price: 50,
            allure: 7,
            type: 'body',
            use: 'single',
        },
    },
    gun: {
        name: 'Sig Sauer 9mm',
        image: 'pics/object/Gun.jpg',
        description: 'This gun will scare away any bad man you might meet!',
        price: 150
    },
    magicTech: {
        laptop: {
            name: 'Laptop',
            image: 'pics/object/Laptop.png',
            description: 'A must have for teenagers!',
            price: 800,
        },
        webcam: {
            name: 'Web cam',
            image: 'pics/personal_items/webcam.jpg',
            description: 'To chat with your friends and family! And not only... (Requires Laptop)',
            price: 500,
        }
    },
    cosmetics: {
        makeup_kit: {
            name: 'Makeup kit',
            image: 'pics/personal_items/cosmetics.jpg',
            description: 'A set of cosmetics for women who want to look stunning and eye-catching!',
            count: 10,
            price: 300,
            use: 'many',
        },
        red_lipstick: {
            name: 'Red lipstick',
            image: 'pics/personal_items/lipsticks/red.jpg',
            description: 'Red lipstick',
            count: 30,
            price: 130,
            use: 'many',
        },
        black_lipstick: {
            name: 'Black lipstick',
            image: 'pics/personal_items/lipsticks/black.jpg',
            description: 'Black lipstick',
            count: 30,
            price: 130,
            use: 'many',
        },
        brown_lipstick: {
            name: 'Brown lipstick',
            image: 'pics/personal_items/lipsticks/brown.jpg',
            description: 'Brown lipstick',
            count: 30,
            price: 130,
            use: 'many',
        },
        violet_lipstick: {
            name: 'Violet lipstick',
            image: 'pics/personal_items/lipsticks/violet.jpg',
            description: 'Violet lipstick',
            count: 30,
            price: 130,
            use: 'many',
        },
        pink_lipstick: {
            name: 'Pink lipstick',
            image: 'pics/personal_items/lipsticks/pink.jpg',
            description: 'Pink lipstick',
            count: 30,
            price: 130,
            use: 'many',
        },
        lipbalm: {
            name: 'Lip balm',
            image: 'pics/personal_items/lipbalm.jpg',
            description: 'Lip balm',
            count: 30,
            price: 100,
            use: 'many',
        },
    },
    pharmacy: {
        birth_control_pills: {
            name: 'Birth control pills',
            image: 'pics/personal_items/birth_control_pills.jpg',
            description: "Who doesn't want a lot of hassle and sleepless nights?",
            count: 10,
            price: 150,
            use: 'many',
        },
        tampons: {
            name: 'Tampons',
            image: 'pics/personal_items/tampons.jpg',
            description: 'Mini dildos!',
            count: 18,
            price: 250,
            use: 'many',
        },
        vitamins: {
            name: 'Vitamins',
            image: 'pics/personal_items/vitamins.jpg',
            description: 'Drink once a day for good health and energy!',
            count: 20,
            price: 200,
            use: 'many',
        },
        pregnancy_test: {
            name: 'Pregnancy test',
            image: 'pics/personal_items/pregnancy_test.jpg',
            description: 'The game started...',
            count: 1,
            price: 100,
            use: 'many',
        },
    },
    dime_time: {
        shampoo: {
            name: 'Shampoo',
            image: 'pics/personal_items/shampoo.jpg',
            description: 'Keeps your body and hair clean',
            count: 20,
            price: 150,
            use: 'many',
        },
        razors: {
            name: 'Razors',
            image: 'pics/personal_items/razors.jpg',
            description: 'Cuts your bush',
            count: 20,
            price: 200,
            use: 'many',
        },
        tampons: {
            name: 'Tampons',
            image: 'pics/personal_items/tampons.jpg',
            description: 'Take on unexpected moments',
            count: 18,
            price: 250,
            use: 'many',
        },
    },
}
window.GAME_ITEMS = GAME_ITEMS
window.GAME_ITEMS_V2 = GAME_ITEMS_V2
